### ISSUE TITLE
Report not finished

### ISSUE THREAD

**Issue by AlexFeix** [MarkWilliams93/DS4D-Assignment-2-3-4#1]
Hey guys!

We still have to finish the report.... Here is my part which describes the data.
[Report_Data.docx](https://github.com/MarkWilliams93/DS4D-Assignment-2-3-4/files/1527621/Report_Data.docx)

**Comment by MarkWilliams93** [comment]
working on it

**Comment by MarkWilliams93** [comment]
[Report_Data.docx](https://github.com/MarkWilliams93/DS4D-Assignment-2-3-4/files/1531474/Report_Data.docx)

updated and spell checked. Please check what I have added

**Comment by luvianmoon** [comment]
I will work with the part that talk about the data visualization.

**Comment by MarkWilliams93** [comment]
[Assignment 3.docx](https://github.com/MarkWilliams93/DS4D-Assignment-2-3-4/files/1536163/Assignment.3.docx)

Final version?

**Comment by AlexFeix** [comment]
I think that's fine!
